#!/bin/bash
#-------- Anuraj ---------#

RED='\033[00;31m'
NC='\033[0m'
GREEN='\033[00;32m'
BLUE='\033[00;34m'
clear
echo -e " "
echo -e "${RED}		[     Openvz Virtualization     ]${NC}"
echo -e "${BLUE}		---------------------------------${NC}"
echo -e " "
PS3='Please Enter Your Choice:- '
options=("Openvz installation" "Template Download" "Container creation" "Destroy Container" "Restart Container"  "Stop Container"  "Quit")
select opt in "${options[@]}"
do
    case $opt in
"Openvz installation")
		if ping -c 5  www.google.com &> /dev/null ;then		
            echo -e "${GREEN}Openvz Installation${NC}"
		else
			echo -e "${RED}No Internet Access${NC}"
		exit
	fi
		echo -ne ""${GREEN}Enabling  Openvz Repo:-${NC}
	rm -rf /etc/yum.repos.d/openvz.repo &> /dev/null
 if	wget -P /etc/yum.repos.d/ http://ftp.openvz.org/openvz.repo  &> /dev/null ; then
	rpm --import http://ftp.openvz.org/RPM-GPG-Key-OpenVZ &> /dev/null
		echo -e "${RED}YES${NC}"
		
	else
		echo -e "${RED}NO${NC}"
	exit
fi
		echo -ne "${GREEN}Installing Necessary Packages:-${NC}"
	if	/usr/bin/yum  install vzkernel  vzctl vzquota ploop  -y &> /dev/null ; then
		echo -e "${RED}YES${NC}"
		echo -e "${BLUE}Reboot System To Choose Openvz Kernel${NC}"
	exit
         else
		echo -e "${RED}Packages are not Installed check your network connection${NC}"
exit	
fi 
;;
"Template Download")
            	echo -e "${GREEN}Downloading Templates${NC}"
		service vz restart &> /dev/null
		chkconfig vz on &> /dev/null
		rm -rf /vz/template/cache/* $> /dev/null

	


		if wget -P /vz/template/cache/  http://download.openvz.org/template/precreated/centos-6-x86_64-minimal.tar.gz  &> /dev/null ; then
			echo -e "${BLUE}Template Downloading completed..${NC}"
		else
			echo -e "${RED}Templates Not Downloaded${NC}"
		fi

;;
"Container creation")
            echo -e "${GREEN}Container Creation${NC}"
		NAME=`ls /vz/template/cache/ | cut -d"." -f1`
		read -p "Enter Container Id:- " ID
#		echo -e "${GREEN}Running container Hosts Are : ${HOST}${NC}"
		read -p "Enter container Ip Address:- " IP
		read -p "Enter Container Host Name:-  " NAM
		read -p "Enter Container Password:- " PASS
		echo -e "${GREEN}Creating Container${NC}"
		/usr/sbin/vzctl create ${ID}  --layout simfs --ostemplate ${NAME} &> /dev/null
		/usr/sbin/vzctl  set  ${ID}  --ipadd  ${IP}  --save    &>/dev/null
		/usr/sbin/vzctl set ${ID} --nameserver 8.8.8.8 --save  &> /dev/null
		/usr/sbin/vzctl set ${ID} --hostname $NAM --save &> /dev/null
		/usr/sbin/vzctl set ${ID} --diskspace 4G --save &> /dev/null
		/usr/sbin/vzctl set ${ID} --userpasswd root:${PASS} &> /dev/null
		/usr/sbin/vzctl  start  ${ID} &> /dev/null
		clear
		echo -e "${NC}----------------------------------------------------------------------------------"
		vzlist -a
		echo -e "----------------------------------------------------------------------------------"
		echo -e "${NC}"
echo -e "Options........
1) Openvz installation	4) Destroy Container	7) Quit
2) Template Download	5) Restart Container
3) Container creation	6) Stop Container"

;;
"Destroy Container")
echo "Selected Destroy"
	clear
	vzlist -a
	echo "----------------------------------------------------------------------"
	read -p  "Enter CTID To Destroy:-" NUM
	/usr/sbin/vzctl stop ${NUM} &> /dev/null
	/usr/sbin/vzctl  destroy ${NUM} &> /dev/null
clear
vzlist -a
echo "----------------------------------------------------------------------"
echo -e "Options........
1) Openvz installation	4) Destroy Container	7) Quit
2) Template Download	5) Restart Container
3) Container creation	6) Stop Container
"
;;

"Restart Container")
	clear
	vzlist -a
	read -p "Enter CTID To Restart:" CTID &> /dev/null
	/usr/sbin/vzctl restart ${CTID}

;;

"Stop Container")
	clear
	vzlist -a
	read -p "Enter CTID to Stop:" CTID1 &> /dev/null
;;

        "Quit")
	clear
            break
            ;;
        *) echo -e "${RED}*********Invalid option**********${NC}
${BLUE}Valid Options are.......${NC}
1) Openvz installation 3) Container creation   5) Quit
2) Template Download   4) Destroy Container ";;
    esac
done

